var countryList = [
    "Afghanistan",
    "Burkina Faso",
    "Burundi",
    "Cameroon",
    "Central African Republic",
    "Chad",
    "Democratic Republic of the Congo",
    "Ethiopia",
    "Haiti",
    "Iraq",
    "Libya",
    "Mali",
    "Myanmar",
    "Niger",
    "Nigeria",
    "occupied Palestinian territory",
    "Somalia",
    "South Sudan",
    "Sudan",
    "Syria",
    "Ukraine",
    "Venezuela (Bolivarian Republic of)",
    "Yemen"
];

// var countryList = [
//     "AFG",
//     "BFA",
//     "BDI",
//     "CMR",
//     "CAF",
//     "TCD",
//     "COD",
//     "ETH",
//     "HTI",
//     "IRQ",
//     "LBY",
//     "MLI",
//     "MMR",
//     "NER",
//     "NGA",
//     "PSE",
//     "SOM",
//     "SSD",
//     "SDN",
//     "SYR",
//     "UKR",
//     "VEN",
//     "YEM"
// ];
