var countryList = [
    "Afghanistan",
    "Burkina Faso",
    "Burundi",
    "Cameroon",
    "Central African Republic",
    "Chad",
    "Democratic Republic of the Congo",
    "Ethiopia",
    "Haiti",
    "Iraq",
    "Libya",
    "Mali",
    "Myanmar",
    "Niger",
    "Nigeria",
    "Occupied Palestinian Territory",
    "Somalia",
    "South Sudan",
    "Sudan",
    "Syria",
    "Ukraine",
    "Venezuela",
    "Yemen"
];

// var countryList = [
//     "AFG",
//     "BFA",
//     "BDI",
//     "CMR",
//     "CAF",
//     "TCD",
//     "COD",
//     "ETH",
//     "HTI",
//     "IRQ",
//     "LBY",
//     "MLI",
//     "MMR",
//     "NER",
//     "NGA",
//     "PSE",
//     "SOM",
//     "SSD",
//     "SDN",
//     "SYR",
//     "UKR",
//     "VEN",
//     "YEM"
// ];
